### PR TITLE
✅ Fixed broadcast adapter func and random anime/manga endpoint

### LINKED ISSUE #542: 🐛 Anime::getBroadcastAttribute() function causes an error when adapting the "broadcast" attribute value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```TypeError```
Status code: ```0```
Message: ```App\Anime::adaptBroadcastValue(): Argument #1 ($broadcast) must be of type array|string|null, MongoDB\Model\BSONDocument given, called in /app/app/Anime.php on line 120```
Trace: ```/app/app/Anime.php on line 410```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/random/anime

### Environment

```markdown
- OS: Debian 12
- Browser: Chrome 126
- Docker: 26.1.4
```

### Anything else?

My api is in a docker container and got data (i executed the indexer and anime fetching was done). 

Get random manga works
Get random characters return the same one

### PR DESCRIPTION
**Pull request by pushrbx**
- There was a change recently in the jikan lib, which might have changed the code path for the resolution of the broadcast attribute of the anime items. I've added a hotfix for it to make it work for now. (Fixes #542)
- The random endpoints of anime and manga were not respecting `sfw` and `unapproved` parameters. This PR fixes that.

### CODE REVIEW

**Comment by N-Pu** [comment]
Responses are still not filtering (sfw, unspecified - didn't check that).

**Comment by pushrbx** [comment]
> Responses are still not filtering (sfw, unspecified - didn't check that). But I'll hope you fix it soon. Thanks for the response the other day.

Did you checkout this version from this PR and check it locally? On my end out of 100 tries there were no nsfw items when I've added the `sfw` parameter.

**Comment by N-Pu** [comment]
> > Responses are still not filtering (sfw, unspecified - didn't check that). But I'll hope you fix it soon. Thanks for the response the other day.
> 
> @N-Pu Did you checkout this version from this PR and check it locally? On my end out of 100 tries there were no nsfw items when I've added the `sfw` parameter.

Well, I actually tried it. Link didn't change in any case, so whenever sfw=true or =false I sometimes get responses with hentai. Maybe I'm doing something wrong on my end.

**Comment by pushrbx** [comment]
@N-Pu Just to be clear: this version / fix is not on `https://api.jikan.moe` yet. Are you self-hosting? If yes and you cloned this version, and the bug still persist, then there is a problem.

**Comment by N-Pu** [comment]
No-no, I'm not self hosting. I get the idea. Will wait when this commit will merge into master branch.

**Review by irfan-dahir — APPROVED** [review]
LGTM

**Pull request merged**
