### PR TITLE
Remove duplicate parameter from "/schedules" path

### PR DESCRIPTION
**Pull request by BarraFiqaulihi**
Found it when I was importing the API to Postman.

Screenshot (133)

### CODE REVIEW

**Comment by pushrbx** [comment]
Could you please also check if this thing is also duplicated anywhere in the code comments? We generate these json files based on the comments/annotations we add in the code.

**Comment by BarraFiqaulihi** [comment]
Sure, will look into it.

**Comment by BarraFiqaulihi** [comment]
Done 👌.

**Review by pushrbx — APPROVED** [review]
lgtm

**Pull request merged**
